import type { OperationDef, ResearchDef } from '../types';

// ──────────────────────────────────────────────────────────────────────────────
// Research tree
// ──────────────────────────────────────────────────────────────────────────────

export const RESEARCH_DEFS: ResearchDef[] = [
  {
    id: 'basic_metallurgy',
    name: 'Basic Metallurgy',
    description: 'Electrolytic reduction of metal ores for aluminium production.',
    tooltip: 'The Hall-Héroult process (1886) uses electrolysis to smelt aluminium from alumina at 960°C. A single modern smelter draws 500 MW continuously. Aluminium\'s specific strength of 190 kN·m/kg makes it indispensable for lightweight space structures — the ISS alone contains 17,000 kg of aluminium alloy.',
    rpCost: 500,
    requires: [],
    unlocks: ['aluminum_smelter'],
  },
  {
    id: 'organic_chemistry',
    name: 'Organic Chemistry',
    description: 'Pyrolysis of PAN precursor fibres and methane/LOX propellant synthesis.',
    tooltip: 'Carbon fibre is made by pyrolysing polyacrylonitrile (PAN) at 1000–3000°C in an inert atmosphere, yielding fibres with 3,500–7,000 MPa tensile strength — five times steel at one-fifth the weight. Methalox propellant (CH₄/LOX) enables full-stack reusability, since methane can be synthesised on Mars via the Sabatier reaction.',
    rpCost: 600,
    requires: [],
    unlocks: ['carbon_extractor', 'propellant_plant'],
  },
  {
    id: 'advanced_mining',
    name: 'Rare Earth Extraction',
    description: 'Solvent extraction and ion-exchange separation of lanthanide series elements.',
    tooltip: 'Despite the name, rare earth elements are abundant in Earth\'s crust but occur at low concentrations. Separation exploits minute ionic radius differences across 17 lanthanides using HDEHP solvent extraction. China produces ~85% of global REE supply. Neodymium magnets and lanthanum-doped catalysts are irreplaceable in avionics and traction drives.',
    rpCost: 400,
    requires: [],
    unlocks: ['ree_mine'],
  },
  {
    id: 'silicon_processing',
    name: 'Silicon Processing',
    description: 'Czochralski crystal growth for 9N semiconductor-grade polysilicon.',
    tooltip: 'Semiconductor silicon requires 99.9999999% (9N) purity. The Czochralski process pulls a single-crystal boule from molten silicon at 1415°C using a seed crystal rotating at 10–30 RPM. A single 300 mm wafer contains ~10 billion transistors. Solar-grade silicon (6N) is less pure but suffices for space photovoltaics.',
    rpCost: 800,
    requires: ['basic_metallurgy'],
    unlocks: ['silicon_refinery'],
  },
  {
    id: 'structural_engineering',
    name: 'High-Load Structural Design',
    description: 'FEA for megascale tensile structures under combined orbital mechanics loads.',
    tooltip: 'The Space Elevator anchor station must withstand ~10 million tonnes of tensile load. FEA models solve systems with 10⁸ degrees of freedom. The tether simultaneously experiences Coriolis forces from climber vehicles, lunar tidal forces, and electrodynamic drag from Earth\'s magnetosphere — each varying non-linearly over a 27-day cycle.',
    rpCost: 1000,
    requires: ['basic_metallurgy'],
    unlocks: ['structural_fab'],
  },
  {
    id: 'cnt_synthesis',
    name: 'Carbon Nanotube Synthesis',
    description: 'CVD growth and wet-spinning of macroscopic CNT yarns approaching theoretical tensile limits.',
    tooltip: 'Single-wall CNTs have a theoretical tensile strength of 100–130 GPa — over 50× the best steel. Current CVD-grown CNT yarns achieve 1–10 GPa in bulk form. We are on the early slope of the S-curve: achieving 50 GPa in cable form would make geosynchronous elevators viable. This is the defining materials science challenge of the programme.',
    rpCost: 2000,
    requires: ['organic_chemistry'],
    unlocks: ['cnt_fabricator'],
  },
  {
    id: 'photovoltaics',
    name: 'Space-Grade Photovoltaics',
    description: 'Multi-junction III-V solar cells optimised for AM0 spectrum and radiation hardness.',
    tooltip: 'Triple-junction GaInP/GaAs/Ge cells achieve 28–33% efficiency in space vs ~22% for terrestrial silicon, because there is no atmosphere to absorb UV and IR. Radiation hardness is achieved via 200 μm cerium-doped cover glass and n-on-p cell architecture. The geosynchronous anchor station will need ~500 MW of continuous generation.',
    rpCost: 1200,
    requires: ['silicon_processing'],
    unlocks: ['solar_panel_fab'],
  },
  {
    id: 'precision_electronics',
    name: 'Radiation-Hardened Electronics',
    description: 'RHBD CMOS ASICs for flight computers in high-TID GEO environments.',
    tooltip: 'Geosynchronous orbit accumulates ~100 krad(Si) total ionising dose per year through the Van Allen belts. Radiation-hardened chips use annular (enclosed-geometry) transistors to prevent SEU inversion channels. Triple modular redundancy (TMR) flight computers vote across three identical units to mask bit-flips from cosmic ray strikes.',
    rpCost: 1500,
    requires: ['silicon_processing'],
    unlocks: ['avionics_fab'],
  },
  {
    id: 'life_support_tech',
    name: 'Closed-Loop Life Support',
    description: 'ECLSS water recovery, CO₂ reduction, and N₂/O₂ atmosphere management for multi-year habitation.',
    tooltip: 'The ISS ECLSS recovers ~93% of water from urine and condensate via vacuum distillation and catalytic oxidation. The Sabatier reactor converts CO₂ + H₂ → CH₄ + H₂O. For the Space Elevator anchor station, 2-year crew rotations demand near-100% loop closure — every kilogram resupplied costs ~$20,000 at geosynchronous altitude.',
    rpCost: 2500,
    requires: ['structural_engineering'],
    unlocks: ['life_support_fab'],
  },
  {
    id: 'advanced_research_methods',
    name: 'Advanced Research Methods',
    description: 'ML-accelerated materials discovery, open-access platforms, and pre-registered experimental pipelines.',
    tooltip: 'Graph neural networks trained on materials databases can predict crystal properties (bandgap, formation energy, elastic moduli) orders of magnitude faster than DFT. This approach identified 380,000 new stable crystalline materials in 2023 — a decade of conventional research compressed into months. Applied to CNT synthesis, it is shortcutting 10-year parameter spaces.',
    rpCost: 1500,
    requires: [],
    unlocks: ['advanced_research'],
  },
];

export const RESEARCH_BY_ID = Object.fromEntries(
  RESEARCH_DEFS.map(d => [d.id, d])
) as Record<string, ResearchDef>;

// ──────────────────────────────────────────────────────────────────────────────
// Operations
// ──────────────────────────────────────────────────────────────────────────────

export const OPERATION_DEFS: OperationDef[] = [
  // ── Extraction ─────────────────────────────────────────────────────────────
  {
    id: 'steel_mine',
    name: 'Steel Mine & Foundry',
    description: 'Iron ore extraction and basic oxygen furnace steelmaking.',
    tooltip: 'Modern BOF steelmaking converts a 300-tonne heat of iron in 40 minutes. Electric arc furnaces (EAF) can recycle scrap at 400–700 kWh/tonne. The Space Elevator tether anchor and ground station alone will require ~50,000 tonnes of high-grade structural steel with tightly controlled carbon content.',
    category: 'extraction',
    annualCostM: 420,
    outputs: [{ resource: 'steel', annualAmount: 12000 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 6,
  },
  {
    id: 'carbon_extractor',
    name: 'Carbon Fibre Plant',
    description: 'PAN-precursor pyrolysis to produce aerospace-grade carbon fibre tow.',
    tooltip: 'Carbon fibre production begins with stretching and oxidising PAN fibres at 200–300°C, then carbonising at 1000–1500°C in N₂. The resulting T800-grade fibre (5,880 MPa, 294 GPa modulus) is 70% lighter than steel per unit strength. Global capacity is ~180,000 tonnes/year — a bottleneck for space construction programmes.',
    category: 'extraction',
    annualCostM: 380,
    outputs: [{ resource: 'carbon', annualAmount: 4800 }],
    inputs: [],
    requires: [],
    requiresResearch: 'organic_chemistry',
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'aluminum_smelter',
    name: 'Aluminium Smelter',
    description: 'Hall-Héroult electrolytic reduction of alumina to high-purity aluminium.',
    tooltip: 'A typical smelter contains 300–500 electrolytic cells, each drawing 150–350 kA at 4–5 V. The molten cryolite bath (Na₃AlF₆) at 960°C dissolves alumina, which is reduced at the carbon cathode. Each tonne of aluminium requires ~14,000 kWh of electricity — making smelters the largest industrial electricity consumers globally.',
    category: 'extraction',
    annualCostM: 350,
    outputs: [{ resource: 'aluminum', annualAmount: 8000 }],
    inputs: [],
    requires: [],
    requiresResearch: 'basic_metallurgy',
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'silicon_refinery',
    name: 'Silicon Refinery',
    description: 'Siemens process and Czochralski crystal growth for semiconductor-grade polysilicon.',
    tooltip: 'Starting from quartz sand (SiO₂), silicon is reduced with coke in an electric arc furnace to 98% metallurgical grade, then purified via the Siemens process (CVD at 1100°C using trichlorosilane) to 9N purity. Czochralski boules are sliced into 300 mm wafers using diamond wire saws with 80 μm kerf.',
    category: 'extraction',
    annualCostM: 300,
    outputs: [{ resource: 'silicon', annualAmount: 2400 }],
    inputs: [],
    requires: [],
    requiresResearch: 'silicon_processing',
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'ree_mine',
    name: 'REE Mining Complex',
    description: 'Bayan Obo-style open-pit mining with HDEHP solvent extraction separation.',
    tooltip: 'REE separation exploits the 0.2 Å variation in ionic radius across the lanthanide series. HDEHP (di-2-ethylhexyl phosphoric acid) solvent extraction runs through 20–50 mixer-settler stages to achieve 99.9% purity per element. Residual thorium and uranium from ore processing require licensed radioactive waste management.',
    category: 'extraction',
    annualCostM: 500,
    outputs: [{ resource: 'ree', annualAmount: 600 }],
    inputs: [],
    requires: [],
    requiresResearch: 'advanced_mining',
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'propellant_plant',
    name: 'Propellant Plant',
    description: 'Steam methane reforming and air-separation LOX production for methalox propellant.',
    tooltip: 'Liquid methane (LCH₄, bp −161°C) and liquid oxygen (LOX, bp −183°C) are stored in vacuum-jacketed cryogenic tanks. The mixture\'s specific impulse of 380 s (vacuum) is slightly lower than hydrogen/LOX (450 s), but methane\'s much higher density and the ability to synthesise it on Mars via CO₂ + H₂ makes it the propellant of choice for reusable deep-space vehicles.',
    category: 'extraction',
    annualCostM: 460,
    outputs: [{ resource: 'methalox', annualAmount: 24000 }],
    inputs: [],
    requires: [],
    requiresResearch: 'organic_chemistry',
    unlocksAtPhase: 0,
    maxInstances: 5,
  },

  // ── Manufacturing ──────────────────────────────────────────────────────────
  {
    id: 'cnt_fabricator',
    name: 'CNT Cable Fabricator',
    description: 'CVD growth reactors and wet-spinning lines for geosynchronous-grade CNT tether cable.',
    tooltip: 'A Space Elevator tether must support its own weight over 36,000 km while a climber vehicle (20 tonnes) ascends at 200 km/h. Required cross-sectional tapering yields a taper ratio of ~10 for 100 GPa material. Current best CNT yarn achieves ~10 GPa — we are producing near-specification cable for the first time in history.',
    category: 'manufacturing',
    annualCostM: 840,
    outputs: [{ resource: 'cntCable', annualAmount: 120 }],
    inputs: [
      { resource: 'carbon', annualAmount: 2400 },
      { resource: 'ree',    annualAmount: 200 },
    ],
    requires: ['carbon_extractor', 'ree_mine'],
    requiresResearch: 'cnt_synthesis',
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'avionics_fab',
    name: 'Avionics Fabrication',
    description: 'Radiation-hardened flight computers, IMUs, and command/telemetry systems for climber vehicles.',
    tooltip: 'Climber vehicles traverse the Van Allen belts multiple times per trip, accumulating ~10 krad(Si) TID per ascent/descent cycle. RHBD ASICs with TMR processing boards add ~40 kg per vehicle but are mandatory above 2000 km altitude. The avionics suite also includes redundant LIDAR for cable tracking and autonomous fault response.',
    category: 'manufacturing',
    annualCostM: 620,
    outputs: [{ resource: 'avionics', annualAmount: 240 }],
    inputs: [
      { resource: 'silicon', annualAmount: 1200 },
      { resource: 'ree',     annualAmount: 100 },
    ],
    requires: ['silicon_refinery', 'ree_mine'],
    requiresResearch: 'precision_electronics',
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'structural_fab',
    name: 'Structural Assembly',
    description: 'Automated welding and CNC machining of large structural components for the anchor and ground station.',
    tooltip: 'The Earth anchor station must absorb 10⁷ tonne horizontal tether force while resisting seismic loads and storm surge (ocean-platform sites). The geosynchronous counterweight is a 600,000-tonne structure assembled in orbit from pre-launched modules — the largest structure humanity has ever built.',
    category: 'manufacturing',
    annualCostM: 560,
    outputs: [{ resource: 'structural', annualAmount: 1800 }],
    inputs: [
      { resource: 'steel',    annualAmount: 6000 },
      { resource: 'aluminum', annualAmount: 2000 },
    ],
    requires: ['steel_mine', 'aluminum_smelter'],
    requiresResearch: 'structural_engineering',
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'solar_panel_fab',
    name: 'Solar Panel Factory',
    description: 'Triple-junction GaInP/GaAs/Ge space solar panels with 30% AM0 efficiency.',
    tooltip: 'Space solar panels generate ~270 W/m² (AM0) vs ~200 W/m² for terrestrial panels. Each panel is tested in a solar simulator (Xe arc lamp, 1 AU spectrum) before launch. The anchor station\'s 500 MW requirement means ~1.85 km² of panel area — assembled robotically in GEO over a 3-year construction window.',
    category: 'manufacturing',
    annualCostM: 480,
    outputs: [{ resource: 'solarPanels', annualAmount: 360 }],
    inputs: [
      { resource: 'silicon',  annualAmount: 800 },
      { resource: 'aluminum', annualAmount: 600 },
    ],
    requires: ['silicon_refinery', 'aluminum_smelter'],
    requiresResearch: 'photovoltaics',
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'life_support_fab',
    name: 'Life Support Systems',
    description: 'ECLSS modules, habitat pressure vessels, and closed-loop water/atmosphere management.',
    tooltip: 'The anchor station crews of 12–24 people require 2 kg/day of food, 2.5 L/day of water, and 0.84 kg/day of O₂ per person. Without recycling, annual resupply would cost ~$800M at GEO. Closed-loop life support reduces consumable delivery to <50 kg/person/year — making permanent habitation economically viable.',
    category: 'manufacturing',
    annualCostM: 700,
    outputs: [{ resource: 'lifeSupport', annualAmount: 180 }],
    inputs: [
      { resource: 'aluminum',   annualAmount: 1000 },
      { resource: 'structural', annualAmount: 400 },
    ],
    requires: ['structural_fab'],
    requiresResearch: 'life_support_tech',
    unlocksAtPhase: 0,
    maxInstances: 2,
  },

  // ── R&D ────────────────────────────────────────────────────────────────────
  {
    id: 'research_lab',
    name: 'Research Laboratory',
    description: 'Directed materials science and orbital mechanics research for the Space Elevator programme.',
    tooltip: 'Fundamental space elevator research typically costs $2–5M per researcher-year at national labs. DARPA\'s ISAAC programme (Innovative Space-based Radar Auxiliary Capabilities) and ESA\'s Clean Space initiative have co-funded early-stage CNT cable research since 2008. Each lab generates ~4 publications/year, each cited ~12 times on average.',
    category: 'rd',
    annualCostM: 320,
    outputs: [{ resource: 'rp', annualAmount: 1200 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 8,
  },
  {
    id: 'advanced_research',
    name: 'Advanced Research Campus',
    description: 'Multi-disciplinary campus with ML-accelerated discovery pipelines and shared characterisation facilities.',
    tooltip: 'Advanced campuses co-locate computational materials science (high-performance GPU clusters for DFT/MD simulation) with experimental synthesis labs and characterisation suites (TEM, XPS, nanoindentation). This reduces the iteration cycle from months to days. MIT\'s Research Laboratory of Electronics is the archetype: 800 researchers, $120M/year budget.',
    category: 'rd',
    annualCostM: 680,
    outputs: [{ resource: 'rp', annualAmount: 3600 }],
    inputs: [],
    requires: ['research_lab'],
    requiresResearch: 'advanced_research_methods',
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
];

export const OPERATIONS_BY_ID = Object.fromEntries(
  OPERATION_DEFS.map(d => [d.id, d])
) as Record<string, OperationDef>;
