import type { OperationDef } from '../types';

export const OPERATION_DEFS: OperationDef[] = [
  // ── Extraction ─────────────────────────────────────────────────────────────
  {
    id: 'steel_mine',
    name: 'Steel Mine & Foundry',
    description: 'Iron ore extraction and basic steel production.',
    category: 'extraction',
    annualCostM: 420,
    outputs: [{ resource: 'steel', annualAmount: 12000 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 6,
  },
  {
    id: 'carbon_extractor',
    name: 'Carbon Fibre Plant',
    description: 'Processes coal and petroleum into carbon fibre stock.',
    category: 'extraction',
    annualCostM: 380,
    outputs: [{ resource: 'carbon', annualAmount: 4800 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'aluminum_smelter',
    name: 'Bauxite Smelter',
    description: 'Hall-Héroult electrolytic aluminium production.',
    category: 'extraction',
    annualCostM: 350,
    outputs: [{ resource: 'aluminum', annualAmount: 8000 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'silicon_refinery',
    name: 'Silicon Refinery',
    description: 'Produces semiconductor-grade polysilicon.',
    category: 'extraction',
    annualCostM: 300,
    outputs: [{ resource: 'silicon', annualAmount: 2400 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'ree_mine',
    name: 'REE Mining Complex',
    description: 'Extracts and separates rare earth elements.',
    category: 'extraction',
    annualCostM: 500,
    outputs: [{ resource: 'ree', annualAmount: 600 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'propellant_plant',
    name: 'Propellant Plant',
    description: 'Produces liquid methane and liquid oxygen from natural gas.',
    category: 'extraction',
    annualCostM: 460,
    outputs: [{ resource: 'methalox', annualAmount: 24000 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 5,
  },

  // ── Manufacturing ──────────────────────────────────────────────────────────
  {
    id: 'cnt_fabricator',
    name: 'CNT Cable Fabricator',
    description: 'Spins carbon nanotube fibres into elevator tether cable.',
    category: 'manufacturing',
    annualCostM: 840,
    outputs: [{ resource: 'cntCable', annualAmount: 120 }],
    inputs: [
      { resource: 'carbon', annualAmount: 2400 },
      { resource: 'ree',    annualAmount: 200 },
    ],
    requires: ['carbon_extractor', 'ree_mine'],
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'avionics_fab',
    name: 'Avionics Fab',
    description: 'Manufactures flight computers, sensors, and control systems.',
    category: 'manufacturing',
    annualCostM: 620,
    outputs: [{ resource: 'avionics', annualAmount: 240 }],
    inputs: [
      { resource: 'silicon', annualAmount: 1200 },
      { resource: 'ree',     annualAmount: 100 },
    ],
    requires: ['silicon_refinery', 'ree_mine'],
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'structural_fab',
    name: 'Structural Assembly',
    description: 'Fabricates large structural components from steel and aluminium.',
    category: 'manufacturing',
    annualCostM: 560,
    outputs: [{ resource: 'structural', annualAmount: 1800 }],
    inputs: [
      { resource: 'steel',    annualAmount: 6000 },
      { resource: 'aluminum', annualAmount: 2000 },
    ],
    requires: ['steel_mine', 'aluminum_smelter'],
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
  {
    id: 'solar_panel_fab',
    name: 'Solar Panel Factory',
    description: 'Produces high-efficiency photovoltaic arrays.',
    category: 'manufacturing',
    annualCostM: 480,
    outputs: [{ resource: 'solarPanels', annualAmount: 360 }],
    inputs: [
      { resource: 'silicon',  annualAmount: 800 },
      { resource: 'aluminum', annualAmount: 600 },
    ],
    requires: ['silicon_refinery', 'aluminum_smelter'],
    unlocksAtPhase: 0,
    maxInstances: 3,
  },
  {
    id: 'life_support_fab',
    name: 'Life Support Systems',
    description: 'Manufactures ECLSS modules, habitats, and pressure vessels.',
    category: 'manufacturing',
    annualCostM: 700,
    outputs: [{ resource: 'lifeSupport', annualAmount: 180 }],
    inputs: [
      { resource: 'aluminum',  annualAmount: 1000 },
      { resource: 'structural', annualAmount: 400 },
    ],
    requires: ['structural_fab'],
    unlocksAtPhase: 0,
    maxInstances: 2,
  },

  // ── R&D ────────────────────────────────────────────────────────────────────
  {
    id: 'research_lab',
    name: 'Research Laboratory',
    description: 'Fundamental research advancing space elevator technology.',
    category: 'rd',
    annualCostM: 320,
    outputs: [{ resource: 'rp', annualAmount: 1200 }],
    inputs: [],
    requires: [],
    unlocksAtPhase: 0,
    maxInstances: 8,
  },
  {
    id: 'advanced_research',
    name: 'Advanced Research Campus',
    description: 'Multi-disciplinary campus with accelerated RP generation.',
    category: 'rd',
    annualCostM: 680,
    outputs: [{ resource: 'rp', annualAmount: 3600 }],
    inputs: [],
    requires: ['research_lab'],
    unlocksAtPhase: 0,
    maxInstances: 4,
  },
];

export const OPERATIONS_BY_ID = Object.fromEntries(
  OPERATION_DEFS.map(d => [d.id, d])
) as Record<string, OperationDef>;
